### PR TITLE
Fix warning_handler and pass error code to error_handler

### PR DESCRIPTION
**Pull request by hoelzro**
Addresses issues #19 and #20.  Tests are still needed for both.

### CODE REVIEW

**Comment by hoelzro** [comment]
@petdance Because we want to be able to check it against error codes from `POSIX` rather than a stringy error code that could be translated into a different language

**Comment by dolmen** [comment]
@hoelzro Just passing $! should be enough. It will be kept as a dual var trough the function call. Let the receiver do the numification if he wants.

**Comment by hoelzro** [comment]
I believe that I explicitly numified because `File::Next` could pass other, non-`$!` error codes into the error handler, and I didn't want error handlers to depend on the detail that the passed-in value was a dualvar.

**Comment by dolmen** [comment]
This fix has been released in https://metacpan.org/release/PETDANCE/File-Next-1.13_01.

I can't wait to see an ack release with a fixed test suite.

**Comment by dolmen** [comment]
Issue petdance/ack2#485 has been linked to here since Feb 2015.

**Pull request merged**
